### PR TITLE
fix bound weapon spell

### LINKED ISSUE #689: Bound Bow fails to fire bound arrows and occasionally crashes game
## Version of Skyrim Together
1.6.7

## Description

Upon casting and using the Bound Bow skill while playing with others, the game initially shows that I have "Bound Arrow (0)" before then saying "No Arrows Equipped". Every additional recast shows "No Arrows Equipped". If I select a regular arrow (like an iron arrow), it will use that arrow I have equipped instead of bound arrows. I also crashed a few times when drawing back an arrow with Bound Bow using regular arrows, but I was unable to replicate the crashes consistently. This occurs even if I do not have any bows or arrows in my inventory. The bug is most consistently replicated next to another player.

Related ObjectIDs|
---------------|
[Bound Bow - 00058F60](https://en.uesp.net/wiki/Skyrim:Bound_Weapon)|

## Steps to reproduce

1. Start the game.
2. Load a saved game.
3. Connect to a server.
4. Stand near another player. 
5. Cast Bound Bow
6. Fire Bound Bow
7. "No Arrows Equipped".

## Reproduction rate
Consistently unable to spawn in or use bound arrows near other players. Infrequently crashes instead of showing "No Arrows Equipped" (5% of the time?).

## Expected result
Bound arrows should be equipped and fired instead of having to use other types of arrows or experiencing "No Arrows Equipped" or a crash.

### PR DESCRIPTION
**Pull request by otsffs**
close #689

### CODE REVIEW

File: Code/client/Games/Skyrim/Forms/MagicItem.cpp [hunk 1]
```diff
@@ -31,6 +31,17 @@ bool MagicItem::IsBuffSpell() const noexcept
     }
 }
 
+bool MagicItem::IsBoundWeaponSpell() noexcept
+{
+    for (EffectItem* pEffect : listOfEffects)
+    {
+        if (pEffect->pEffectSetting->eArchetype == EffectArchetypes::ArchetypeID::kBoundWeapon)
```
Comment (maximegmd) [inline Code/client/Games/Skyrim/Forms/MagicItem.cpp:38]: are we sure pEffectSetting is always valid?

**Review by maximegmd — CHANGES_REQUESTED** [review]

File: Code/client/Games/Skyrim/Forms/MagicItem.cpp (hunk 1 above)
Comment (otsffs) [reply Code/client/Games/Skyrim/Forms/MagicItem.cpp]: Add nullptr checks
